# 🎌 Hybrid Anime Recommendation System

Welcome to the **Hybrid Anime Recommendation System**! This document serves as the comprehensive A-to-Z guide for the project. Whether you are a new developer or a DevOps engineer, this guide will help you understand the system architecture, machine learning models, Continuous Integration/Continuous Deployment (CI/CD) pipelines, and Google Cloud Platform (GCP) configurations.

---

NOTE : This project is focused on MLOPS

## 🎯 1. Project Overview

At its core, this project is a Machine Learning application designed to provide highly relevant anime recommendations to users.

### 🌟 Key Features
- **Hybrid Recommendation Engine:** Combines Content-Based Filtering (genre, format, scores) with Collaborative Filtering (user behavior) using **TensorFlow** neural networks and embedding techniques.
- **Smart Search:** Features a lightning-fast, debounced autocomplete search bar powered by a predefined dataset of valid anime titles.
- **Modern UI/UX:** Built with React + Vite, featuring a sleek, dark-themed glassmorphism aesthetic tailored for anime enthusiasts.
- **Dynamic Posters:** Leverages a batched GraphQL query to **AniList API** as the primary image source, keeping API calls to a minimum (1 call for all 10 posters), and seamlessly falls back to the **Jikan (MyAnimeList)** API for missing cover arts.
- **Robust CI/CD Pipeline:** Fully automated from code commit to a live Kubernetes cluster on GCP.

---

## 🏗️ 2. Technology Stack

### Backend & Machine Learning
- **Language / Framework:** Python (v3.11), Flask (REST API)
- **Data Engineering:** Pandas, NumPy
- **Machine Learning:** TensorFlow (Deep Learning / Embeddings)
- **Data Version Control:** DVC (`google-cloud-storage` remote)

### Frontend
- **Framework:** React 18
- **Build Tool:** Vite
- **Styling:** Vanilla CSS (Glassmorphism, CSS Modules style organization)

### DevOps & Cloud Infrastructure (GCP)
- **Containerization:** Docker (Multi-stage builds)
- **CI/CD Orchestration:** Jenkins
- **Artifacts:** Google Cloud Storage (GCS) for DVC, Google Container/Artifact Registry (GCR) for Docker images
- **Orchestration / Hosting:** Google Kubernetes Engine (GKE) Autopilot

---

## 🚀 3. CI/CD Architecture (The Pipeline)

My deployment is fully automated using a **Jenkins Pipeline** triggered by GitHub pushes. Here is the step-by-step lifecycle of code from local to production:

```text
🧑‍💻 You push code to GitHub (main branch)
        ↓
🤖 Jenkins detects the change (or you click "Build Now")
        ↓
📥 Checkout: Jenkins creates a workspace and pulls the latest code from GitHub.
        ↓
🐍 Setup Environment: Jenkins sets up a Python virtual environment (`anime_venv`) and installs `requirements.txt`.
        ↓
📦 DVC Pull: Jenkins authenticates with GCP and runs `dvc pull` to download heavy ML models, model checkpoints, and processed datasets from Google Cloud Storage (GCS) into the `artifacts/` folder.
        ↓
🐳 Docker Build: Jenkins utilizes our Multi-Stage Dockerfile:
    • Stage 1: Compiles the React frontend using Node.js logic and Vite (`npm run build`).
    • Stage 2: Wraps the built React files into a lightweight Python image alongside TensorFlow system dependencies and the Flask API.
        ↓
🌍 Docker Push: The freshly built image is tagged and pushed to Google Container Registry (GCR).
        ↓
☸️ Kubernetes Deploy: Jenkins executes `kubectl apply -f deployment.yaml`.
    • Pulls the newest image.
    • Rolls out the updated pods to the `ml-app-cluster`.
    • Checks Readiness/Liveness via `/api/health`.
        ↓
🎉 Live on GKE: Your new code is successfully routing traffic through the GCP Load Balancer!
```

---

## ☁️ 4. Google Cloud Platform (GCP) Setup

This project uses GCP as the backbone of our CI/CD and deployment. We have explicitly enabled the following APIs:
1. **Google Container Registry API / Artifact Registry API:** Used for storing versioned Docker images generated by Jenkins.
2. **Kubernetes Engine API:** Orchestrates the deployment via a fully managed GKE Autopilot cluster (`ml-app-cluster`).
3. **Cloud Storage API:** Used heavily by DVC to maintain our large static metadata and ML models, keeping GitHub clean and preventing size limit errors.

**Important GKE Details:**
- **Cluster Name:** `ml-app-cluster`
- **Workload Details:** A Deployment named `anime-recommender` executing pods powered by our Flask/React Hybrid image.
- **Exposure:** Service type `LoadBalancer` exposing the internet to port `80`, mapping to container port `5000`.

---

## 💻 5. Local Development Guide

Want to run the codebase locally for testing or development? Because the Flask backend also serves the frontend in production, you have a specific dual-terminal setup for rapid UI/UX and API testing.

**Terminal 1 — Flask API Backend**
```bash
# Navigate to project root
cd e:\hybrid_Anime_Recommendation_System

# 1. Activate virtual environment (Windows Powershell example)
.\anime_venv\Scripts\activate

# 2. Install requirements if you haven't already
pip install -r requirements.txt

# 3. Pull DVC artifacts (Ensures models are available locally)
dvc pull

# 4. Run the Flask API directly in debug mode
python app.py

# (API will continuously listen on http://localhost:5000)
```

**Terminal 2 — React Frontend (Dev Server)**
```bash
# Open a new terminal and navigate to the frontend folder
cd e:\hybrid_Anime_Recommendation_System\frontend

# 1. Install node dependencies
npm install

# 2. Start the extremely fast Vite development server
npm run dev

# (Vite typically listens on http://localhost:5173 - changes hot-reload instantly)
```
*Note: Ensure your frontend API calls internally route to `http://localhost:5000` during development mode!*

---

## 📁 6. Core Project Structure

```text
/hybrid_Anime_Recommendation_System
├── .github/          # (Optional) GitHub templates
├── .dvc/             # Data Version Control configuration & remotes
├── artifacts/        # [DVC Tracked] ML Models, encoders, & processed dataframes
├── config/           # Centralized configuration (paths, model hyperparameters)
├── frontend/         # React Application
│   ├── src/          # React components, styles, and utilities
│   │   ├── utils/    # Contains posterFetcher.js checking AniList & Jikan
│   ├── dist/         # (Generated) Production build output used by Flask
│   └── vite.config.js
├── pipelines/        # Model prediction & training pipeline logic
├── src/              # Raw data processing and model architecture source code
├── utils/            # Helper scripts (e.g., getting anime metadata)
├── app.py            # Main Flask Entrypoint (API & Static File Server)
├── Dockerfile        # Multi-stage build manifest for GCP
├── deployment.yaml   # Kubernetes configuration (Deployments + LoadBalancer)
├── Jenkinsfile       # The pipeline logic executed by the Jenkins orchestrator
└── requirements.txt  # Python package list
```

---

## 🔌 7. Main API Endpoints

- **`GET /api/health`:** Readiness probe check used explicitly by GKE to know if a given pod is safe to receive traffic (waiting for large TF models to load).
- **`GET /api/search?q={text}`:** Fast autocomplete searching possible anime titles bounding to user input.
- **`POST /api/recommend`:** The primary workhorse endpoint. Resolves an `anime_name` alongside configurable weight biases to output 10 hybrid recommendations.
- **`GET /api/anime/{name}`:** Fetches detailed metadata for a single anime.

Welcome to the team, and happy coding! 🚀

